---
  - name: create the webapp root
    file: 
      path: "{{ webapp_root }}"
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}" 
      mode: 0755
      state: directory
    become: true

  - name: clone webapp
    git:
      repo: https://github.com/philbert/sample_flask_app.git
      dest: "{{ webapp_dir }}"

  - name: setup virtualenv for webapp
    pip:
      requirements: "{{ webapp_dir }}/requirements.txt"
      virtualenv: "{{ webapp_root }}/virtenv"

  - name: install gunicorn
    pip:
      name: gunicorn
      virtualenv: "{{ webapp_root }}/virtenv"

  - name: enable gunicorn service and socket
    service: name={{ item }} enabled=yes state=started
    with_items:
      - "gunicorn.service"
      - "gunicorn.socket"
    become: true
    become_user: root
        
